import { useEffect, useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { ArrowLeft, Plus, Sparkle } from "phosphor-react-native";
import { api } from "@/src/api";
import { colors } from "@/src/theme";
type Store={id:string;brand_id:string;store_code:string;name:string;parent_store_id?:string|null;store_type:string;city?:string;state?:string;postal_code?:string;address_line1?:string;timezone?:string;phone?:string;email?:string;active:boolean};
type Ctx={active_brand:any;brands:any[];is_super_admin:boolean};
const blank:any={store_code:"",name:"",parent_store_id:null,store_type:"regular",address_line1:"",city:"",state:"",postal_code:"",country:"US",timezone:"America/Chicago",phone:"",email:"",active:true};
export default function BrandStores(){
 const r=useRouter(),[ctx,setCtx]=useState<Ctx|null>(null),[brandId,setBrandId]=useState(""),[stores,setStores]=useState<Store[]>([]),[form,setForm]=useState<any>(blank),[editing,setEditing]=useState<Store|null>(null),[err,setErr]=useState(""),[ok,setOk]=useState("");
 async function loadStores(id:string){setStores((await api.get<{stores:Store[]}>("/brand/stores?brand_id="+encodeURIComponent(id)+"&include_inactive=true")).stores||[])}
 useEffect(()=>{api.get<Ctx>("/context").then(async x=>{setCtx(x);const id=x.active_brand?.id||x.brands?.[0]?.id||"";setBrandId(id);if(id)await loadStores(id)}).catch((e:any)=>setErr(e.message))},[]);
 const brand=ctx?.brands?.find(b=>b.id===brandId)||ctx?.active_brand,parents=useMemo(()=>stores.filter(x=>x.id!==editing?.id&&x.active),[stores,editing?.id]);
 async function selectBrand(id:string){setBrandId(id);setEditing(null);setForm({...blank});await api.put("/context",{brand_id:id,store_id:null});await loadStores(id)}
 async function save(){try{setErr("");const p={...form,brand_id:brandId};editing?await api.put("/brand/stores/"+editing.id,p):await api.post("/brand/stores",p);setOk(editing?"Store updated":"Store created");setEditing(null);setForm({...blank});await loadStores(brandId)}catch(e:any){setErr(e.message)}}
 return <ScrollView style={{backgroundColor:colors.soft}} contentContainerStyle={s.page}>
  <View style={s.top}><Pressable style={s.back} onPress={()=>r.push("/admin")}><ArrowLeft size={18}/><Text>Admin</Text></Pressable><View style={s.brand}><Sparkle size={16} color={colors.primary}/><Text style={s.bold}>Brand & Stores</Text></View></View>
  <View style={s.hero}><View style={{flex:1}}><Text style={s.kicker}>BRAND ADMINISTRATION</Text><Text style={s.title}>{brand?.name||"Brand"} Stores</Text><Text style={s.muted}>Manage regular stores, mother stores, central plants and pickup/drop-off locations.</Text></View><Pressable style={s.primary} onPress={()=>{setEditing(null);setForm({...blank})}}><Plus size={16} color="#fff"/><Text style={s.primaryText}>Add Store</Text></Pressable></View>
  {ctx?.is_super_admin&&ctx.brands?.length>1?<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{ctx.brands.map(b=><Pressable key={b.id} style={[s.chip,brandId===b.id&&s.chipOn]} onPress={()=>selectBrand(b.id)}><Text style={[s.chipText,brandId===b.id&&s.chipTextOn]}>{b.name}</Text></Pressable>)}</ScrollView>:null}
  {err?<Text style={s.err}>{err}</Text>:null}{ok?<Text style={s.ok}>{ok}</Text>:null}
  <View style={s.grid}>{stores.map(x=><View key={x.id} style={s.card}><Pressable style={{flex:1}} onPress={()=>{setEditing(x);setForm({...x})}}><Text style={s.cardTitle}>{x.name}</Text><Text style={s.muted}>{x.store_code} · {x.store_type.replaceAll("_"," ")}</Text><Text style={s.muted}>{[x.city,x.state,x.postal_code].filter(Boolean).join(", ")||"Address not configured"}</Text>{x.parent_store_id?<Text style={s.muted}>Parent: {stores.find(p=>p.id===x.parent_store_id)?.name||"Store"}</Text>:null}</Pressable><View style={{alignItems:"flex-end",gap:7}}><Text style={{fontWeight:"900",color:x.active?colors.success:colors.danger}}>{x.active?"Active":"Inactive"}</Text>{x.active?<Pressable style={s.useBtn} onPress={async()=>{await api.put("/context",{brand_id:brandId,store_id:x.id});setOk("Active context: "+x.name)}}><Text style={s.useText}>Use Store</Text></Pressable>:null}</View></View>)}</View>
  <View style={s.panel}><Text style={s.section}>{editing?"Edit Store":"Add Store"}</Text><View style={s.row}><Field label="Store name"><TextInput style={s.input} value={form.name||""} onChangeText={v=>setForm({...form,name:v})}/></Field><Field label="Store code"><TextInput style={s.input} value={form.store_code||""} autoCapitalize="characters" onChangeText={v=>setForm({...form,store_code:v.toUpperCase()})}/></Field></View><Text style={s.label}>Store type</Text><View style={s.chips}>{[["regular","Regular"],["mother_store","Mother / Hub"],["central_plant","Central Plant"],["dropoff","Pickup / Drop-off"]].map(([v,l])=><Pressable key={v} style={[s.chip,form.store_type===v&&s.chipOn]} onPress={()=>setForm({...form,store_type:v})}><Text style={[s.chipText,form.store_type===v&&s.chipTextOn]}>{l}</Text></Pressable>)}</View><Text style={s.label}>Parent / Mother Store</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}><Pressable style={[s.chip,!form.parent_store_id&&s.chipOn]} onPress={()=>setForm({...form,parent_store_id:null})}><Text style={[s.chipText,!form.parent_store_id&&s.chipTextOn]}>None</Text></Pressable>{parents.map(p=><Pressable key={p.id} style={[s.chip,form.parent_store_id===p.id&&s.chipOn]} onPress={()=>setForm({...form,parent_store_id:p.id})}><Text style={[s.chipText,form.parent_store_id===p.id&&s.chipTextOn]}>{p.name}</Text></Pressable>)}</ScrollView><View style={s.row}><Field label="Address"><TextInput style={s.input} value={form.address_line1||""} onChangeText={v=>setForm({...form,address_line1:v})}/></Field><Field label="City"><TextInput style={s.input} value={form.city||""} onChangeText={v=>setForm({...form,city:v})}/></Field></View><View style={s.row}><Field label="State"><TextInput style={s.input} value={form.state||""} autoCapitalize="characters" onChangeText={v=>setForm({...form,state:v.toUpperCase()})}/></Field><Field label="ZIP"><TextInput style={s.input} value={form.postal_code||""} keyboardType="number-pad" onChangeText={v=>setForm({...form,postal_code:v})}/></Field><Field label="Timezone"><TextInput style={s.input} value={form.timezone||""} onChangeText={v=>setForm({...form,timezone:v})}/></Field></View><View style={s.row}><Field label="Phone"><TextInput style={s.input} value={form.phone||""} onChangeText={v=>setForm({...form,phone:v})}/></Field><Field label="Email"><TextInput style={s.input} value={form.email||""} keyboardType="email-address" autoCapitalize="none" onChangeText={v=>setForm({...form,email:v})}/></Field></View><View style={s.toggle}><Text style={s.bold}>Active</Text><Switch value={form.active!==false} onValueChange={v=>setForm({...form,active:v})}/></View><Pressable style={[s.primary,{alignSelf:"flex-start"}]} onPress={save}><Text style={s.primaryText}>{editing?"Save Store":"Create Store"}</Text></Pressable></View>
 </ScrollView>
}
function Field({label,children}:{label:string;children:any}){return <View style={s.field}><Text style={s.label}>{label}</Text>{children}</View>}
const s=StyleSheet.create({page:{padding:18,maxWidth:1120,width:"100%",alignSelf:"center",gap:14},top:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:10},back:{flexDirection:"row",gap:6,alignItems:"center"},brand:{flexDirection:"row",gap:6,alignItems:"center"},bold:{fontWeight:"900",color:colors.ink},hero:{backgroundColor:"#fff",borderWidth:1,borderColor:colors.border,borderRadius:20,padding:20,flexDirection:"row",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:12},kicker:{fontSize:10,fontWeight:"900",color:colors.primary},title:{fontSize:30,fontWeight:"900",color:colors.ink},muted:{color:colors.muted,fontSize:12,marginTop:3},primary:{backgroundColor:colors.primary,minHeight:44,borderRadius:12,paddingHorizontal:15,paddingVertical:11,flexDirection:"row",gap:6,alignItems:"center",justifyContent:"center"},primaryText:{color:"#fff",fontWeight:"900"},grid:{flexDirection:"row",flexWrap:"wrap",gap:10},card:{flex:1,minWidth:250,backgroundColor:"#fff",borderWidth:1,borderColor:colors.border,borderRadius:16,padding:15,flexDirection:"row",alignItems:"center",gap:8},cardTitle:{fontSize:17,fontWeight:"900",color:colors.ink},panel:{backgroundColor:"#fff",borderWidth:1,borderColor:colors.border,borderRadius:18,padding:18,gap:10},section:{fontSize:18,fontWeight:"900",color:colors.ink},row:{flexDirection:"row",gap:10,flexWrap:"wrap"},field:{flex:1,minWidth:210},label:{fontSize:10,fontWeight:"900",color:colors.muted,textTransform:"uppercase",marginBottom:5},input:{borderWidth:1,borderColor:colors.border,borderRadius:11,minHeight:44,paddingHorizontal:12,paddingVertical:10},chips:{flexDirection:"row",gap:7,flexWrap:"wrap"},chip:{borderWidth:1,borderColor:colors.border,borderRadius:999,paddingHorizontal:12,paddingVertical:9},chipOn:{backgroundColor:colors.primary,borderColor:colors.primary},chipText:{fontSize:12,fontWeight:"800",color:colors.ink},chipTextOn:{color:"#fff"},toggle:{backgroundColor:colors.soft,borderRadius:11,padding:10,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},useBtn:{borderWidth:1,borderColor:colors.primary,borderRadius:9,paddingHorizontal:9,paddingVertical:6},useText:{fontSize:11,fontWeight:"900",color:colors.primary},err:{color:colors.danger},ok:{color:colors.success,fontWeight:"800"}});