import { useEffect, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { ArrowLeft, Gift, Sparkle, UserCircle } from "phosphor-react-native";
import { api } from "@/src/api";
import { colors } from "@/src/theme";
import { Code128 } from "@/src/Code128";

type Customer={id:string;name:string;phone:string;email?:string;notes?:string;reward_points?:number;referral_code?:string};
type Order={id:string;order_number:string;status:string;payment_status:string;total:number;created_at?:string;fulfillment_type?:string};
type Reward={id:string;points:number;description?:string;created_at?:string;transaction_type?:string};
type Referral={id:string;referral_code:string;status:string;referred_customer_id?:string|null;reward_points?:number;created_at?:string};
type Subscription={id:string;plan_id:string;plan_name:string;frequency:string;status:string;next_pickup_date?:string|null;service_address?:string;service_postal_code?:string};
type Plan={id:string;name:string;frequency:string;discount_percent:number;minimum_order:number};
type Profile={customer:Customer;orders:Order[];rewards:{enabled?:boolean;balance:number;transactions:Reward[]};referrals:{enabled?:boolean;referral_code:string;referrals:Referral[]};capabilities?:{rewards_enabled?:boolean;referrals_enabled?:boolean;subscriptions_enabled?:boolean;ai_assistance_enabled?:boolean};summary:{order_count:number;lifetime_value:number;open_orders:number;paid_orders:number}};

export default function CustomerProfile(){
  const router=useRouter();
  const params=useLocalSearchParams<{id?:string}>();
  const id=String(params.id||"");
  const [profile,setProfile]=useState<Profile|null>(null);
  const [err,setErr]=useState("");
  const [subscriptions,setSubscriptions]=useState<Subscription[]>([]);
  const [plans,setPlans]=useState<Plan[]>([]);
  const [showEnroll,setShowEnroll]=useState(false);
  const [planId,setPlanId]=useState("");
  const [nextPickup,setNextPickup]=useState("");
  const [serviceAddress,setServiceAddress]=useState("");
  const [servicePostalCode,setServicePostalCode]=useState("");
  const [aiSummary,setAiSummary]=useState<any>(null);
  const [aiBusy,setAiBusy]=useState(false);
  const [payments,setPayments]=useState<any[]>([]);
  const [notifications,setNotifications]=useState<any[]>([]);
  async function load(){if(!id)return;try{const [p,s,pl,pay,n]=await Promise.all([api.get<Profile>("/customers/"+encodeURIComponent(id)+"/profile"),api.get<{subscriptions:Subscription[]}>("/customers/"+encodeURIComponent(id)+"/subscriptions"),api.get<{plans:Plan[]}>("/subscriptions/plans"),api.get<{payments:any[]}>("/customers/"+encodeURIComponent(id)+"/payments"),api.get<{notifications:any[]}>("/customers/"+encodeURIComponent(id)+"/notifications")]);setProfile(p);setSubscriptions(s.subscriptions||[]);setPlans(pl.plans||[]);setPayments(pay.payments||[]);setNotifications(n.notifications||[]);}catch(e:any){setErr(e.message||"Could not load customer");}}
  useEffect(()=>{load();},[id]);
  async function enroll(){if(!planId){setErr("Select a subscription plan");return;}try{await api.post("/customers/"+id+"/subscriptions",{plan_id:planId,next_pickup_date:nextPickup||null,service_address:serviceAddress,service_postal_code:servicePostalCode});setShowEnroll(false);setPlanId("");setNextPickup("");await load();}catch(e:any){setErr(e.message||"Could not create subscription");}}
  async function setStatus(sub:Subscription,status:string){try{await api.put("/subscriptions/"+sub.id,{status});await load();}catch(e:any){setErr(e.message||"Could not update subscription");}}
  async function generateSummary(){setAiBusy(true);setErr("");try{setAiSummary(await api.get<any>("/ai/customers/"+id+"/summary"));}catch(e:any){setErr(e.message||"Could not generate summary");}finally{setAiBusy(false);}}
  if(!profile)return <View style={s.loading}><Text>{err||"Loading customer…"}</Text></View>;
  const c=profile.customer;
  return <ScrollView style={{backgroundColor:colors.soft}} contentContainerStyle={s.page}>
    <View style={s.top}><Pressable onPress={()=>router.push("/customers")} style={s.back}><ArrowLeft size={18} color={colors.ink}/><Text style={s.backText}>Customers</Text></Pressable><View style={s.brand}><Sparkle size={16} color={colors.primary}/><Text style={s.brandText}>FabClean</Text></View></View>
    <View style={s.header}><View style={s.avatar}><UserCircle size={34} color={colors.primary}/></View><View style={{flex:1}}><Text style={s.kicker}>CUSTOMER PROFILE</Text><Text style={s.title}>{c.name}</Text><Text style={s.sub}>{c.phone}{c.email?" · "+c.email:""}</Text></View><Pressable style={s.newBtn} onPress={()=>router.push({pathname:"/walk-in",params:{customerId:c.id}})}><Text style={s.newText}>New Order</Text></Pressable></View>
    {profile.capabilities?.ai_assistance_enabled!==false?<View style={s.panel}><View style={s.sectionHead}><Text style={s.sectionTitle}>AI customer summary</Text><Pressable onPress={generateSummary}><Text style={s.linkText}>{aiBusy?"Working…":aiSummary?"Refresh":"Generate"}</Text></Pressable></View>{aiSummary?<><Text style={s.aiText}>{aiSummary.summary}</Text><Text style={s.aiNote}>Staff assistance only · Review before acting.</Text></>:<Text style={s.meta}>Generate a concise summary from this customer’s FabClean history.</Text>}</View>:null}
    <View style={s.panel}><Text style={s.sectionTitle}>Customer barcode</Text><Text style={s.meta}>Show this barcode on the customer’s phone and scan it during order intake.</Text><View style={s.customerBarcode}><Code128 value={"CUSTOMER:"+c.id} height={58} moduleWidth={1.5}/><Text style={s.customerBarcodeText}>{"CUSTOMER:"+c.id}</Text></View></View>
    <View style={s.summary}>
      <Metric label="Orders" value={String(profile.summary.order_count)}/><Metric label="Lifetime" value={"$"+profile.summary.lifetime_value.toFixed(2)}/><Metric label="Open" value={String(profile.summary.open_orders)}/>{profile.capabilities?.rewards_enabled!==false?<Metric label="Rewards" value={String(profile.rewards.balance)}/>:null}{profile.capabilities?.referrals_enabled!==false?<Metric label="Referral" value={profile.referrals.referral_code||"—"}/>:null}
    </View>
    {profile.capabilities?.subscriptions_enabled!==false?<View style={s.panel}><View style={s.sectionHead}><Text style={s.sectionTitle}>Subscriptions</Text><Pressable onPress={()=>setShowEnroll(!showEnroll)}><Text style={s.linkText}>{showEnroll?"Cancel":"Add Subscription"}</Text></Pressable></View>{showEnroll?<View style={s.enrollBox}><Text style={s.meta}>Choose a plan</Text><View style={s.planRow}>{plans.map(p=><Pressable key={p.id} onPress={()=>setPlanId(p.id)} style={[s.planChip,planId===p.id&&s.planChipOn]}><Text style={[s.planChipText,planId===p.id&&s.planChipTextOn]}>{p.name} · {p.frequency}</Text></Pressable>)}</View><TextInput style={s.input} placeholder="Next pickup YYYY-MM-DD" value={nextPickup} onChangeText={setNextPickup}/><TextInput style={s.input} placeholder="Pickup address" value={serviceAddress} onChangeText={setServiceAddress}/><TextInput style={s.input} placeholder="Postal code" value={servicePostalCode} onChangeText={setServicePostalCode}/><Pressable style={s.newBtn} onPress={enroll}><Text style={s.newText}>Save Subscription</Text></Pressable></View>:null}{subscriptions.length===0?<Text style={s.meta}>No active or previous subscriptions.</Text>:subscriptions.map(sub=><View key={sub.id} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{sub.plan_name}</Text><Text style={s.meta}>{sub.frequency} · {sub.status}{sub.next_pickup_date?" · Next "+sub.next_pickup_date:""}</Text></View><View style={s.subActions}>{sub.status==="active"?<Pressable onPress={()=>setStatus(sub,"paused")}><Text style={s.linkText}>Pause</Text></Pressable>:sub.status==="paused"?<Pressable onPress={()=>setStatus(sub,"active")}><Text style={s.linkText}>Resume</Text></Pressable>:null}{sub.status!=="cancelled"?<Pressable onPress={()=>setStatus(sub,"cancelled")}><Text style={s.cancelText}>Cancel</Text></Pressable>:null}</View></View>)}</View>:null}
    <View style={s.panel}><View style={s.sectionHead}><Text style={s.sectionTitle}>Customer communications</Text><Text style={s.meta}>Automatic SMS + email only at critical stages</Text></View>{notifications.filter((n:any)=>["order_received","ready_for_pickup"].includes(n.notification_type)&&["sms","email"].includes(n.channel)).length===0?<Text style={s.meta}>No automatic customer messages recorded yet.</Text>:notifications.filter((n:any)=>["order_received","ready_for_pickup"].includes(n.notification_type)&&["sms","email"].includes(n.channel)).map((n:any)=><View key={n.id} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{n.notification_type.replaceAll("_"," ")} · {String(n.channel).toUpperCase()}</Text><Text style={s.meta}>{n.message}</Text><Text style={[s.messageStatus,n.status==="sent"?s.sent:n.status==="failed"?s.failed:null]}>{n.status}</Text></View></View>)}</View>
    <View style={s.panel}><Text style={s.sectionTitle}>Payment history</Text>{payments.length===0?<Text style={s.meta}>No payment transactions yet.</Text>:payments.map((p:any)=><View key={p.id} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{p.receipt_number}</Text><Text style={s.meta}>{p.transaction_type} · {p.payment_method} · {p.created_at?new Date(p.created_at).toLocaleString():""}</Text></View><Text style={s.amount}>{Number(p.amount||0)<0?"-$"+Math.abs(Number(p.amount||0)).toFixed(2):"$"+Number(p.amount||0).toFixed(2)}</Text></View>)}</View>
    <View style={s.panel}><Text style={s.sectionTitle}>Order history</Text>{profile.orders.length===0?<Text style={s.meta}>No orders yet.</Text>:profile.orders.map(o=><Pressable key={o.id} style={s.row} onPress={()=>router.push({pathname:"/order-detail",params:{id:o.id}})}><View style={{flex:1}}><Text style={s.rowTitle}>{o.order_number}</Text><Text style={s.meta}>{o.fulfillment_type||"walk_in"} · {o.status} · {o.payment_status}</Text></View><Text style={s.amount}>{"$"+Number(o.total||0).toFixed(2)}</Text></Pressable>)}</View>
    <View style={s.twoCol}>
      {profile.capabilities?.rewards_enabled!==false?<View style={s.panel}><Text style={s.sectionTitle}>Reward activity</Text>{profile.rewards.transactions.length===0?<Text style={s.meta}>No reward activity yet.</Text>:profile.rewards.transactions.map(r=><View key={r.id} style={s.row}><Gift size={18} color={r.points>=0?colors.success:colors.danger}/><View style={{flex:1}}><Text style={s.rowTitle}>{r.description||r.transaction_type||"Reward adjustment"}</Text><Text style={s.meta}>{r.created_at?new Date(r.created_at).toLocaleString():""}</Text></View><Text style={s.amount}>{r.points>0?"+":""}{r.points}</Text></View>)}</View>:null}
      {profile.capabilities?.referrals_enabled!==false?<View style={s.panel}><Text style={s.sectionTitle}>Referral activity</Text><Text style={s.refCode}>{profile.referrals.referral_code||"—"}</Text>{profile.referrals.referrals.length===0?<Text style={s.meta}>No referred customers yet.</Text>:profile.referrals.referrals.map(r=><View key={r.id} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{r.status}</Text><Text style={s.meta}>{r.created_at?new Date(r.created_at).toLocaleDateString():""}</Text></View><Text style={s.amount}>{r.reward_points||0} pts</Text></View>)}</View>:null}
    </View>
  </ScrollView>;
}
function Metric({label,value}:{label:string;value:string}){return <View style={s.metric}><Text style={s.metricValue}>{value}</Text><Text style={s.metricLabel}>{label}</Text></View>}
const s=StyleSheet.create({
  loading:{padding:30},page:{padding:20,maxWidth:1100,width:"100%",alignSelf:"center",gap:16},top:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",gap:10,flexWrap:"wrap"},back:{flexDirection:"row",gap:7,alignItems:"center"},backText:{fontWeight:"800",color:colors.ink},brand:{flexDirection:"row",gap:6,alignItems:"center"},brandText:{fontWeight:"900",color:colors.ink},
  header:{backgroundColor:"#fff",borderWidth:1,borderColor:colors.border,borderRadius:22,padding:22,flexDirection:"row",gap:14,alignItems:"center",flexWrap:"wrap"},avatar:{width:54,height:54,borderRadius:27,backgroundColor:colors.primarySoft,alignItems:"center",justifyContent:"center"},kicker:{fontSize:10,fontWeight:"900",letterSpacing:1.3,color:colors.primary},title:{fontSize:30,fontWeight:"900",color:colors.ink},sub:{color:colors.muted,marginTop:3},newBtn:{backgroundColor:colors.primary,borderRadius:12,minHeight:42,paddingHorizontal:15,paddingVertical:10,alignItems:"center",justifyContent:"center"},newText:{color:"#fff",fontWeight:"900"},
  summary:{flexDirection:"row",gap:10,flexWrap:"wrap"},metric:{flex:1,minWidth:150,backgroundColor:"#fff",borderWidth:1,borderColor:colors.border,borderRadius:16,padding:15},metricValue:{fontSize:21,fontWeight:"900",color:colors.ink},metricLabel:{fontSize:11,color:colors.muted,marginTop:3},
  panel:{flex:1,backgroundColor:"#fff",borderWidth:1,borderColor:colors.border,borderRadius:18,padding:17},sectionHead:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},sectionTitle:{fontSize:18,fontWeight:"900",color:colors.ink,marginBottom:8},row:{paddingVertical:10,borderTopWidth:1,borderTopColor:colors.border,flexDirection:"row",gap:10,alignItems:"center"},enrollBox:{backgroundColor:colors.soft,borderRadius:12,padding:12,marginBottom:10,gap:8},planRow:{flexDirection:"row",flexWrap:"wrap",gap:7},planChip:{borderWidth:1,borderColor:colors.border,borderRadius:999,paddingHorizontal:10,paddingVertical:8},planChipOn:{backgroundColor:colors.primary,borderColor:colors.primary},planChipText:{fontSize:12,fontWeight:"800",color:colors.ink},planChipTextOn:{color:"#fff"},input:{borderWidth:1,borderColor:colors.border,borderRadius:10,padding:10,backgroundColor:"#fff"},linkText:{fontWeight:"900",color:colors.primary},cancelText:{fontWeight:"900",color:colors.danger},subActions:{flexDirection:"row",gap:10,alignItems:"center"},rowTitle:{fontWeight:"900",color:colors.ink},meta:{fontSize:12,color:colors.muted,marginTop:2},amount:{fontWeight:"900",color:colors.ink},twoCol:{flexDirection:"row",gap:14,flexWrap:"wrap"},messageStatus:{fontSize:11,fontWeight:"900",textTransform:"uppercase",marginTop:4},sent:{color:colors.success},failed:{color:colors.danger},refCode:{fontSize:22,fontWeight:"900",color:colors.primary,marginBottom:8},aiText:{fontSize:14,lineHeight:22,color:colors.ink},aiNote:{fontSize:11,color:colors.muted,marginTop:6,fontStyle:"italic"},customerBarcode:{marginTop:12,alignItems:"center",padding:16,backgroundColor:colors.soft,borderRadius:12},customerBarcodeText:{marginTop:8,fontSize:11,fontWeight:"900",color:colors.ink,textAlign:"center"}
});