import { useEffect, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { ArrowLeft, Plus, Sparkle } from "phosphor-react-native";
import { api } from "@/src/api";
import { colors } from "@/src/theme";
type Brand={id:string;name:string;slug:string;legal_name?:string;status:string;primary_email?:string;primary_phone?:string;timezone?:string;store_count?:number};
const blank:any={name:"",slug:"",legal_name:"",status:"active",primary_email:"",primary_phone:"",country:"US",timezone:"America/Chicago",currency:"USD"};
export default function PlatformAdmin(){
 const r=useRouter(),[brands,setBrands]=useState<Brand[]>([]),[form,setForm]=useState<any>(blank),[editing,setEditing]=useState<Brand|null>(null),[err,setErr]=useState(""),[ok,setOk]=useState("");
 async function load(){try{setBrands((await api.get<{brands:Brand[]}>("/platform/brands")).brands||[])}catch(e:any){setErr(e.message)}}
 useEffect(()=>{load()},[]);
 async function save(){try{setErr("");const p={...form,slug:String(form.slug||form.name).toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")};editing?await api.put("/platform/brands/"+editing.id,p):await api.post("/platform/brands",p);setOk(editing?"Brand updated":"Brand created");setEditing(null);setForm({...blank});await load()}catch(e:any){setErr(e.message)}}
 return <ScrollView style={{backgroundColor:colors.soft}} contentContainerStyle={s.page}>
  <View style={s.top}><Pressable style={s.back} onPress={()=>r.push("/admin")}><ArrowLeft size={18}/><Text>Admin</Text></Pressable><View style={s.brand}><Sparkle size={16} color={colors.primary}/><Text style={s.bold}>Platform</Text></View></View>
  <View style={s.hero}><View style={{flex:1}}><Text style={s.kicker}>SUPERADMIN</Text><Text style={s.title}>Brands</Text><Text style={s.muted}>Create and manage SaaS tenants. Brand owners manage stores inside their own brand.</Text></View><Pressable style={s.primary} onPress={()=>{setEditing(null);setForm({...blank})}}><Plus size={16} color="#fff"/><Text style={s.primaryText}>Add Brand</Text></Pressable></View>
  {err?<Text style={s.err}>{err}</Text>:null}{ok?<Text style={s.ok}>{ok}</Text>:null}
  <View style={s.grid}>{brands.map(b=><Pressable key={b.id} style={s.card} onPress={()=>{setEditing(b);setForm({...b})}}><View style={{flex:1}}><Text style={s.cardTitle}>{b.name}</Text><Text style={s.muted}>{b.slug} · {b.status} · {b.store_count||0} stores</Text></View><Text style={s.link}>Edit</Text></Pressable>)}</View>
  <View style={s.panel}><Text style={s.section}>{editing?"Edit Brand":"Add Brand"}</Text><View style={s.row}><Field label="Brand name"><TextInput style={s.input} value={form.name||""} onChangeText={v=>setForm({...form,name:v})}/></Field><Field label="Slug"><TextInput style={s.input} value={form.slug||""} autoCapitalize="none" onChangeText={v=>setForm({...form,slug:v})}/></Field></View><View style={s.row}><Field label="Legal name"><TextInput style={s.input} value={form.legal_name||""} onChangeText={v=>setForm({...form,legal_name:v})}/></Field><Field label="Email"><TextInput style={s.input} value={form.primary_email||""} keyboardType="email-address" autoCapitalize="none" onChangeText={v=>setForm({...form,primary_email:v})}/></Field></View><View style={s.row}><Field label="Phone"><TextInput style={s.input} value={form.primary_phone||""} onChangeText={v=>setForm({...form,primary_phone:v})}/></Field><Field label="Timezone"><TextInput style={s.input} value={form.timezone||""} onChangeText={v=>setForm({...form,timezone:v})}/></Field></View><View style={s.toggle}><Text style={s.bold}>Active</Text><Switch value={form.status!=="suspended"} onValueChange={v=>setForm({...form,status:v?"active":"suspended"})}/></View><Pressable style={[s.primary,{alignSelf:"flex-start"}]} onPress={save}><Text style={s.primaryText}>{editing?"Save Brand":"Create Brand"}</Text></Pressable></View>
 </ScrollView>
}
function Field({label,children}:{label:string;children:any}){return <View style={s.field}><Text style={s.label}>{label}</Text>{children}</View>}
const s=StyleSheet.create({page:{padding:18,maxWidth:1100,width:"100%",alignSelf:"center",gap:14},top:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:10},back:{flexDirection:"row",gap:6,alignItems:"center"},brand:{flexDirection:"row",gap:6,alignItems:"center"},bold:{fontWeight:"900",color:colors.ink},hero:{backgroundColor:"#fff",borderWidth:1,borderColor:colors.border,borderRadius:20,padding:20,flexDirection:"row",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:12},kicker:{fontSize:10,fontWeight:"900",color:colors.primary},title:{fontSize:30,fontWeight:"900",color:colors.ink},muted:{color:colors.muted,fontSize:12,marginTop:3},primary:{backgroundColor:colors.primary,minHeight:44,borderRadius:12,paddingHorizontal:15,paddingVertical:11,flexDirection:"row",gap:6,alignItems:"center",justifyContent:"center"},primaryText:{color:"#fff",fontWeight:"900"},grid:{flexDirection:"row",flexWrap:"wrap",gap:10},card:{flex:1,minWidth:240,backgroundColor:"#fff",borderWidth:1,borderColor:colors.border,borderRadius:16,padding:15,flexDirection:"row",alignItems:"center",gap:8},cardTitle:{fontSize:17,fontWeight:"900",color:colors.ink},link:{color:colors.primary,fontWeight:"900"},panel:{backgroundColor:"#fff",borderWidth:1,borderColor:colors.border,borderRadius:18,padding:18,gap:10},section:{fontSize:18,fontWeight:"900",color:colors.ink},row:{flexDirection:"row",gap:10,flexWrap:"wrap"},field:{flex:1,minWidth:210},label:{fontSize:10,fontWeight:"900",color:colors.muted,textTransform:"uppercase",marginBottom:5},input:{borderWidth:1,borderColor:colors.border,borderRadius:11,minHeight:44,paddingHorizontal:12,paddingVertical:10},toggle:{backgroundColor:colors.soft,borderRadius:11,padding:10,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},err:{color:colors.danger},ok:{color:colors.success,fontWeight:"800"}});