import { useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { api, setStoredSession } from "@/src/api";
import { colors } from "@/src/theme";

export default function SignIn(){
 const router=useRouter(); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [showPassword,setShowPassword]=useState(false); const [name,setName]=useState(""); const [bootstrap,setBootstrap]=useState(false); const [err,setErr]=useState(""); const [busy,setBusy]=useState(false);
 async function signIn(){setBusy(true);setErr("");try{if(bootstrap){await api.post<any>("/auth/bootstrap",{name,email,password});setBootstrap(false);setErr("Owner created. Sign in with the same credentials.");}else{const x=await api.post<any>("/auth/sign-in",{email,password});setStoredSession(x.staff,x.token);router.replace("/");}}catch(e:any){setErr(e.message||"Could not sign in");}finally{setBusy(false);}}
 return <View style={s.page}><View style={s.card}><Text style={s.kicker}>FABCLEAN STAFF</Text><Text style={s.title}>Sign in</Text><Text style={s.sub}>{bootstrap?"Create the first Owner account. This option is available only before a password-enabled owner exists.":"Use your active FabClean staff account."}</Text>{bootstrap?<TextInput style={s.input} placeholder="Owner name" value={name} onChangeText={setName}/>:null}<TextInput style={s.input} placeholder="staff@example.com" autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail}/><View style={s.passwordRow}><TextInput style={s.passwordInput} placeholder="Password" secureTextEntry={!showPassword} value={password} onChangeText={setPassword}/><Pressable onPress={()=>setShowPassword(v=>!v)} style={s.showBtn}><Text style={s.showText}>{showPassword?"Hide":"Show"}</Text></Pressable></View>{err?<Text style={s.err}>{err}</Text>:null}<Pressable style={[s.btn,busy&&{opacity:.5}]} disabled={busy||!email.trim()||password.length<8} onPress={signIn}><Text style={s.btnText}>{busy?"Working…":bootstrap?"Create Owner":"Sign In"}</Text></Pressable><Pressable onPress={()=>{setBootstrap(!bootstrap);setErr("");}}><Text style={s.link}>{bootstrap?"Back to sign in":"First-time owner setup"}</Text></Pressable></View></View>;
}
const s=StyleSheet.create({page:{flex:1,minHeight:620,backgroundColor:colors.soft,alignItems:"center",justifyContent:"center",padding:20},card:{width:"100%",maxWidth:430,backgroundColor:"#fff",borderWidth:1,borderColor:colors.border,borderRadius:22,padding:24},kicker:{fontSize:10,fontWeight:"900",letterSpacing:1.3,color:colors.primary},title:{fontSize:30,fontWeight:"900",color:colors.ink,marginTop:4},sub:{color:colors.muted,marginTop:6,marginBottom:18},input:{borderWidth:1,borderColor:colors.border,borderRadius:12,minHeight:44,paddingHorizontal:13,paddingVertical:11,backgroundColor:"#fff",marginTop:8},passwordRow:{flexDirection:"row",alignItems:"center",borderWidth:1,borderColor:colors.border,borderRadius:12,minHeight:44,backgroundColor:"#fff",marginTop:8},passwordInput:{flex:1,paddingHorizontal:13,paddingVertical:11},showBtn:{paddingHorizontal:12,paddingVertical:10},showText:{fontWeight:"900",color:colors.primary},btn:{backgroundColor:colors.primary,borderRadius:12,minHeight:44,padding:12,alignItems:"center",justifyContent:"center",marginTop:14},btnText:{color:"#fff",fontWeight:"900"},err:{color:colors.danger,marginTop:10},link:{textAlign:"center",color:colors.primary,fontWeight:"800",marginTop:12}});