import { useEffect, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { ArrowLeft, Plus, Sparkle } from "phosphor-react-native";
import { api } from "@/src/api";
import { colors } from "@/src/theme";
type Plan={id:string;name:string;description:string;frequency:string;discount_percent:number;minimum_order:number;active:boolean};
type Upcoming={id:string;customer_name:string;phone:string;plan_name:string;frequency:string;next_pickup_date:string;service_address:string;service_postal_code:string};
export default function Subscriptions(){
 const router=useRouter(); const [plans,setPlans]=useState<Plan[]>([]); const [upcoming,setUpcoming]=useState<Upcoming[]>([]); const [form,setForm]=useState({name:"",description:"",frequency:"weekly",discount_percent:0,minimum_order:0,active:true}); const [err,setErr]=useState(""); const [ok,setOk]=useState("");
 async function load(){try{const [p,u]=await Promise.all([api.get<{plans:Plan[]}>("/subscriptions/plans?include_inactive=true"),api.get<{upcoming:Upcoming[]}>("/subscriptions/upcoming?days=7")]);setPlans(p.plans);setUpcoming(u.upcoming);}catch(e:any){setErr(e.message||"Could not load subscriptions");}}
 useEffect(()=>{load();},[]);
 async function addPlan(){setErr("");setOk("");try{await api.post("/subscriptions/plans",form);setForm({name:"",description:"",frequency:"weekly",discount_percent:0,minimum_order:0,active:true});setOk("Plan added");await load();}catch(e:any){setErr(e.message||"Could not add plan");}}
 async function generateNext(id:string){setErr("");setOk("");try{const x=await api.post<any>("/subscriptions/"+id+"/generate-order",{});setOk(x.created?"Recurring order created. Next pickup: "+x.next_pickup_date:"Order already generated for this pickup.");await load();}catch(e:any){setErr(e.message||"Could not generate recurring order");}}
 return <ScrollView style={{backgroundColor:colors.soft}} contentContainerStyle={s.page}><View style={s.top}><Pressable onPress={()=>router.push("/admin")} style={s.back}><ArrowLeft size={18} color={colors.ink}/><Text style={s.backText}>Admin</Text></Pressable><View style={s.brand}><Sparkle size={16} color={colors.primary}/><Text style={s.brandText}>FabClean Subscriptions</Text></View></View><View style={s.header}><Text style={s.kicker}>RECURRING PICKUPS</Text><Text style={s.title}>Subscriptions</Text><Text style={s.sub}>Simple recurring pickup plans and the next 7 days of scheduled customers.</Text></View>{err?<Text style={s.err}>{err}</Text>:null}{ok?<Text style={s.ok}>{ok}</Text>:null}<View style={s.panel}><Text style={s.sectionTitle}>Add plan</Text><View style={s.row}><TextInput style={s.input} placeholder="Plan name" value={form.name} onChangeText={v=>setForm(x=>({...x,name:v}))}/><TextInput style={s.input} placeholder="Description" value={form.description} onChangeText={v=>setForm(x=>({...x,description:v}))}/></View><View style={s.row}>{["weekly","biweekly","monthly"].map(x=><Pressable key={x} style={[s.chip,form.frequency===x&&s.chipOn]} onPress={()=>setForm(v=>({...v,frequency:x}))}><Text style={[s.chipText,form.frequency===x&&s.chipTextOn]}>{x}</Text></Pressable>)}<TextInput style={s.smallInput} keyboardType="decimal-pad" placeholder="Discount %" value={String(form.discount_percent)} onChangeText={v=>setForm(x=>({...x,discount_percent:Number(v)||0}))}/><TextInput style={s.smallInput} keyboardType="decimal-pad" placeholder="Minimum" value={String(form.minimum_order)} onChangeText={v=>setForm(x=>({...x,minimum_order:Number(v)||0}))}/><View style={s.toggle}><Text>Active</Text><Switch value={form.active} onValueChange={v=>setForm(x=>({...x,active:v}))}/></View><Pressable style={s.addBtn} onPress={addPlan}><Plus size={16} color="#fff"/><Text style={s.addText}>Add Plan</Text></Pressable></View>{plans.map(p=><View key={p.id} style={s.item}><View><Text style={s.itemName}>{p.name}</Text><Text style={s.meta}>{p.frequency} · {p.discount_percent}% discount · Min ${Number(p.minimum_order).toFixed(2)}</Text></View><Text style={s.meta}>{p.active?"Active":"Inactive"}</Text></View>)}</View><View style={s.panel}><Text style={s.sectionTitle}>Upcoming pickups · next 7 days</Text>{upcoming.length===0?<Text style={s.meta}>No recurring pickups scheduled.</Text>:upcoming.map(x=><View key={x.id} style={s.item}><View style={{flex:1}}><Text style={s.itemName}>{x.customer_name}</Text><Text style={s.meta}>{x.phone} · {x.plan_name} · {x.frequency}</Text><Text style={s.meta}>{x.service_address}{x.service_postal_code?" · "+x.service_postal_code:""}</Text></View><View style={s.upcomingActions}><Text style={s.date}>{x.next_pickup_date}</Text><Pressable style={s.generateBtn} onPress={()=>generateNext(x.id)}><Text style={s.generateText}>Generate Next Order</Text></Pressable></View></View>)}</View></ScrollView>;
}
const s=StyleSheet.create({page:{padding:20,maxWidth:1000,width:"100%",alignSelf:"center",gap:16},top:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",gap:10,flexWrap:"wrap"},back:{flexDirection:"row",gap:7,alignItems:"center"},backText:{fontWeight:"800",color:colors.ink},brand:{flexDirection:"row",gap:6,alignItems:"center"},brandText:{fontWeight:"900",color:colors.ink},header:{backgroundColor:"#fff",borderWidth:1,borderColor:colors.border,borderRadius:22,padding:22},kicker:{fontSize:10,fontWeight:"900",letterSpacing:1.2,color:colors.primary},title:{fontSize:30,fontWeight:"900",color:colors.ink},sub:{color:colors.muted,marginTop:4},panel:{backgroundColor:"#fff",borderWidth:1,borderColor:colors.border,borderRadius:18,padding:18},sectionTitle:{fontSize:18,fontWeight:"900",color:colors.ink,marginBottom:10},row:{flexDirection:"row",gap:8,flexWrap:"wrap",alignItems:"center",marginBottom:10},input:{flex:1,minWidth:220,borderWidth:1,borderColor:colors.border,borderRadius:11,padding:11},smallInput:{width:140,borderWidth:1,borderColor:colors.border,borderRadius:11,padding:11},chip:{borderWidth:1,borderColor:colors.border,borderRadius:999,paddingHorizontal:10,paddingVertical:8},chipOn:{backgroundColor:colors.primary,borderColor:colors.primary},chipText:{fontWeight:"800",color:colors.ink,fontSize:12},chipTextOn:{color:"#fff"},toggle:{minWidth:125,backgroundColor:colors.soft,borderRadius:10,padding:9,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},addBtn:{backgroundColor:colors.primary,borderRadius:11,minHeight:42,paddingHorizontal:13,paddingVertical:10,flexDirection:"row",gap:6,alignItems:"center",justifyContent:"center"},addText:{color:"#fff",fontWeight:"900"},item:{paddingVertical:11,borderTopWidth:1,borderTopColor:colors.border,flexDirection:"row",justifyContent:"space-between",gap:12},itemName:{fontWeight:"900",color:colors.ink},meta:{fontSize:12,color:colors.muted,marginTop:2},date:{fontWeight:"900",color:colors.primary},upcomingActions:{alignItems:"flex-end",gap:7},generateBtn:{backgroundColor:colors.primarySoft,borderRadius:10,paddingHorizontal:10,paddingVertical:8},generateText:{fontSize:12,fontWeight:"900",color:colors.primaryDark},err:{color:colors.danger},ok:{color:colors.success,fontWeight:"800"}});